# coredns
version: '3'
services:

  coredns:
    image: docker.io/coredns/coredns:1.2.6
    command: -conf /data/Corefile
    ports:
      - 53:53/udp
    volumes:
      - ./data:/data/:ro
    restart: always

networks:
  default:
