version: '3'
services:

  app:
    image: localhost:5000/knowledge
    build: ./app/
    depends_on:
      - knowledge_db
    ports:
      - 8002:8080
    volumes:
      - knowledge_app_storage:/root/.knowledge:rw
    restart: always

  knowledge_db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=knowledge_production
    expose:
      - 5432
    volumes:
      - knowledge_db_storage:/var/lib/postgresql/data:rw
    restart: always

networks:
  default:

volumes:
  knowledge_app_storage:
    driver: local
  knowledge_db_storage:
    driver: local
