version: '3'
services:

  portainer:
    image: docker.io/portainer/portainer:1.19.2
    ports:
      - 8000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: portainer.example.com
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: portainer.example.com
      LETSENCRYPT_EMAIL: admin@example.com]

networks:
  default:
