version: '3'
services:

  ############################################################################

  gogs_db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: gogs_user
      POSTGRES_PASSWORD: gogs_pw
      POSTGRES_DB: gogs
    expose:
      - 5432
    volumes:
      - gogs_storage:/data:rw
    restart: always

  app:
    image: gogs/gogs:0.11.53
    environment:
      RUN_CROND: "false"
    depends_on:
      - gogs_db
    ports:
      - 8001:3000
    volumes:
      - gogs_storage:/data:rw
    restart: always

  ############################################################################

networks:
  default:

volumes:
  gogs_storage:
    driver: local
